export const productOptions = [
    "Cement",
    "Steel Rods",
    "Electrical Wires",
    "Safety Gloves",
    "Paint",
    "Nails",
    "Screws",
    "Pvc Pipes",
    "Welding Rods",
    "Hammers",
    "Screwdrivers",
    "Sandpaper",
    "Glue",
    "Measuring Tape",
    "Ladders",
    "Paintbrushes",
    "Socket Wrenches",
    "Electrical Tape",
    "Plumbing Fittings",
    "Wire Connectors",
    "Nuts & Bolts",
    "Cpvc Pipes",
    "Upvc Pipes",
    "Pvc material",
    "Spanners",
    "Brushes",
    "Spanners",
    "Electrical Boxes",
    "Safety Helmets",
    "Drills",
    "Angle Grinders",
    "Power Saws",
    "Tile Cutters",
    "Chisels",
    "Ventilation Fans",
    "Gaskets",
    "Drainage Pipes",
    "Concrete Mixers",
    "Cable Clips",
    "Cutter Blades",
    "Metal Sheets",
    "Laser Levels",
    "Bolts",
    "Paint Rollers",
    "Grout",
    "Sealants",
    "Quick Drying Screws",
    "Measuring Wheels",
    "Ratchet Straps",
    "Extension Cords",
    "Grounding Rods",
    "Threaded Rods",
    "Scaffolding",
    "Rubber Sheets",
    "Drill Bits",
    "Hoses",
    "Angle Brackets",
    "Tap Sets",
    "Tapes",
    "Screw Lock Washers",
    "Plywood",
    "Rebar Supports",
    "Ear Protection",
    "Eye Protection",
    "Caulking Guns",
    "Pipe Insulation",
    "Concrete Admixtures",
    "Wire Cutters",
    "Wire Strippers",
    "Channel Supports",
    "Flooring Adhesives",
    "Screw Lock Washers",
    "Torsion Springs",
    "Metal Studs",
    "Threaded Fasteners",
    "Drill Driver Sets",
    "Leveling Tools",
    "Clamps",
    "Cutting Oils",
    "Caulking Sealant",
    "Cable Ties",
    "Bit Holders",
    "Reinforcing Mesh",
    "Wall Anchors",
    "Impact Drivers",
    "Saw Blades",
    "Rubber Gloves",
    "Steel Mesh",
    "Bench Vises",
    "Extension Rods",
    "Laser Distance Measurers",
    "Bit Brace",
    "Drain Snakes",
    "Torque Wrenches",
    "Wrenches",
    "Impact Wrenches",
    "Plumbing Tools",
    "Electric Motors",
    "Power Drills",
    "Stud Finders",
    "Chalk Lines",
    "Fasteners",
    "Sump Pumps",
    "Work Lights",
    "Spray Guns",
    "Hydraulic Jacks",
    "Metal Cutting Saws",
    "Pipe Wrenches",
    "Woodworking Tools",
    "Roofing Nails",
    "Taps and Dies",
    "Insulation Tape",
    "Pneumatic Tools",
    "Thread Lockers",
    "Wall Saws",
    "Drop Cloths",
    "Expansion Bolts",
    "Diamond Blades",
    "Wire Looms",
    "Cable Crimpers",
    "Flexible Hoses",
    "Bolt Cutters",
    "Magnetic Drills",
    "Screeding Tools",
    "Drain Grates",
    "Hex Keys",
    "Tool Belts",
    "Magnetic Levels",
    "Hand Tools Sets",
    "Construction Adhesives",
    "Socket Sets",
    "Pipes Insulation",
    "Hose Reels",
    "Bolts and Nuts",
    "Tape Measures",
    "Caulking Tools",
    "Diamond Core Bits",
    "Water Pumps",
    "Fiberglass Mesh",
    "Diamond Blades",
    "Caulking Compounds",
    "Epoxy Adhesives",
    "Pipe Cutters",
    "Cordless Drills",
    "Masonry Drill Bits",
    "Heat Guns",
    "Rotary Hammers",
    "Safety Glasses",
    "Shovel Sets",
    "Grout Removers",
    "Work Boots",
    "Concrete Adhesives",
    "Tile Spacers",
    "Pallet Racking",
    "Ventilation Systems",
    "Tightening Tools",
    "Pipe Hangers",
    "Measuring Tapes",
    "Threaded Rods",
    "Hoists",
    "Flooring Tools",
    "Edge Bander Machines",
    "Utility Knives",
    "Cutting Tools",
    "Bit Sets",
    "Safety Vests",
    "Spanner Wrenches",
    "Electrical Outlets",
    "Rebar Ties",
    "Paver Sand",
    "Varnish",
    "Heat Shrink Tubing",
    "Rebar Chairs",
    "Polyurethane Sealants",
    "Hand Saws",
    "Snips",
    "Wire Mesh",
    "Pipe Fitting Tools",
    "Air Compressors",
    "Measuring Wheels",
    "Cable Organizers",
    "Junction Boxes",
    "Gas Detectors",
    "Chain Hoists",
    "Concrete Cutting Tools",
    "Drill Bits Sets",
    "Bolt Extractors",
    "Concrete Vibrators",
    "Pallets",
    "Screwdrivers Sets",
    "Screw Lock Washers",
    "Tool Storage Systems",
    "Rebar Supports",
    "Pipe Benders",
    "Tile Leveling Systems",
    "Concrete Screws",
    "Pipe Reamers",
    "Duct Tapes",
    "Cable Ladders",
    "Stud Anchors",
    "Heat Guns Kits",
    "Angle Braces",
    "Work Gloves",
    "Torque Screwdrivers",
    "Pneumatic Nailers",
    "Saw Horses",
    "Roofing Tools",
    "Measuring Tape Extenders",
    "Laser Levels Kits",
    "Fiber Cement Boards",
    "Chain Hoist Systems",
    "Panel Mounts",
    "Piping Insulation",
    "Insulation Materials",
    "Concrete Cutting Blades",
    "Trowel Sets",
    "Pipe Bending Tools",
    "Concrete Testing Kits",
    "Roofing Nails",
    "Concrete Saw Blades",
    "Ventilation Accessories",
    "Pipe Markers",
    "Leveling Accessories",
    "Concrete Repair Kits",
    "Torque Wrench Sets",
    "Tool Storage Solutions",
    "Concrete Grinding Tools",
    "Pipe Coating Materials",
    "Concrete Overlay Systems",
    "Rebar Fabrication Tools",
    "Concrete Formwork Systems",
    "Structural Supports",
    "Drainage Systems",
    "Wire Trunking Systems",
    "Safety Barriers",
    "Concrete Curing Blankets",
    "Pipe Threaders",
    "Concrete Block Anchors",
    "Heat Gun Accessories",
    "Concrete Patching Compounds",
    "Pipe Cutter Blades",
    "Concrete Expansion Joints",
    "Pipe Locators",
    "Concrete Floor Sealers",
    "Pipe Expander Tools",
    "Concrete Adhesive Sealants",
    "Pipe Expansion Joints",
    "Concrete Insulation Materials",
    "Pipe Expansion Joint Kits",
    "Concrete Stamps",
    "Pipe Expansion Joints Systems",
    "Concrete Waterstop Systems",
    "Pipe Expansion Joint Sealants",
    "Concrete Joint Seals",
    "Pipe Expansion Joint Tools",
    "Concrete Pavers",
    "Pipe Expansion Joint Accessories",
    "Concrete Expansion Joint Fillers",
    "Pipe Expansion Joint Insulation",
    "Concrete Expansion Joint Sealants",
    "Pipe Expansion Joint Systems",
    "Concrete Expansion Joint Systems Kits",
    "Pipe Expansion Joint Tools Kits",
    "Concrete Expansion Joint Systems Accessories",
    "Pipe Expansion Joint Systems Sealants",
    "Concrete Expansion Joint Systems Sealers",
    "Pipe Expansion Joint Systems Insulation",
  ];
  